language: java
jdk:
- oraclejdk8
script: mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: MoGvxgh0+rdvAqZfQhNGgdgavNpQbVST5dVueTo2YADsJqAQVIZCQbf4aThjH8Z9xNFPz+rtcn8HwEEfmK1CkyaANi/1czcRkWcByeFzZJHxVpjjmAxejqB6I9az5KOWcTf/aMZOQQcOxojErRoH3cpQ/CIl5B5NODvNyZndPh4h+Qb59QvTurJ+Qivi4vym8n1WsnuMYkCZ/WTTEMUda5PjhS9/0I4tY+Qk1bXBqJgDxVXEGdkW3krsYElV96v70HYo7qJQYV58u43iZ3mI8R2NMmOq9VimiomB50p9QAoROT127dgodF9YyKJiYXawk0Bxv8bfqlmeiZwCnpXRvHnFn5ZGxNTdj9sPbYB3UP/AVM6SpP6A5mpWzaGLKRun8PzzvueV3C3nV0htOcJDNEereAf6o7sV/nHW4SwO+vq6/lbC9IZKJ7UVisNc+uBB8KVgJ6XCWOHVQ249CoOsLPnAQbWks9xbTyK3nWsk6bAnCHaDHelMYXLfW9g0BGgiOmLT8HEd4E/LZhBizb30fNihDQoI+CA0BvDg/Vnrt940A9fXhx8d7TQ7RkLPjqZyCyrIMX9ylcnSE7CfzLT7d9t9MVojjt+78bwA7isXn53iJuDuPitk3uD/qGLc1nThixX1MRpMyZIHrGkK8t2jtygFD8O8XJCKS4nP3RUELe0=
  app: ayhan-transactionmanager
  on:
    repo: ayhanugurlu/transactionmanager
